events {}

http {
    resolver 127.0.0.11 valid=30s;
    include mime.types;

    upstream api {
        server lissy-be-api:7001;
    }

    server {
        listen 80;

        include /etc/nginx/mime.types;

        root   /home/;

        location /lissy/api {
            proxy_pass http://api/lissy/api/;
        }

        location /lissy/ {
            set $fe http://lissy-fe;
            proxy_pass $fe$request_uri;
        }

        location = /lissy {
            set $fe http://lissy-fe;
            proxy_pass $fe$request_uri/;
        }
    }
}
