FROM node:latest

WORKDIR /backend/

COPY ./backend/package*.json ./

RUN npm install

COPY ./backend/ ./
COPY ../frontend/modules/ ../frontend/modules/
ADD ./env/.env ./

CMD npm run be-api-docker