CREATE EXTENSION IF NOT EXISTS postgis CASCADE;
CREATE TABLE IF NOT EXISTS rail (gid SERIAL PRIMARY KEY, geom GEOMETRY, conns INT[]);
CREATE TABLE IF NOT EXISTS road (gid SERIAL PRIMARY KEY, geom GEOMETRY, conns INT[]);
CREATE TABLE IF NOT EXISTS tram (gid SERIAL PRIMARY KEY, geom GEOMETRY, conns INT[]);
CREATE TABLE IF NOT EXISTS stops (id SERIAL PRIMARY KEY, stop_name TEXT, latLng GEOMETRY, zone_id TEXT,
    parent_station INT, CONSTRAINT parent_station FOREIGN KEY(parent_station) REFERENCES stops(id), wheelchair_boarding INT, is_active BOOLEAN);